apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: main
          image: {{ required ".Values.image is required" .Values.image }}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 30m
              memory: 20Mi
            limits:
              cpu: 60m
              memory: 40Mi
